### ISSUE TITLE
Epimorphism {X} f

### ISSUE THREAD

**Issue by JoelSjogren** [fredefox/cat#6]
Hi, nice formalization.

Shouldn't Epimorphism be a pi type in X?

    Epimorphism : {X : Object } → (f : Arrow A B) → Set ℓb
    Epimorphism {X} f = (g₀ g₁ : Arrow B X) → g₀ <<< f ≡ g₁ <<< f → g₀ ≡ g₁

vs

    Epimorphism : (f : Arrow A B) → Set ℓb
    Epimorphism f = {X : Object} → (g₀ g₁ : Arrow B X) → g₀ <<< f ≡ g₁ <<< f → g₀ ≡ g₁

**Comment by fredefox** [comment]
Absolutely! Nice catch. 9ee05e1a36a0141273b351845bf36f773d6407fe fixes this.
